### ISSUE TITLE
[Bug / FR] Support brew install

### ISSUE THREAD

**Issue by hu1buerger** [kilpkonn/gtm-enhanced#70]
I installed gtm-enhanced for IntelliJ from the JetBrains store and got gtm from brew `brew tap git-time-metric/gtm; brew install gtm`.

When starting IntelliJ with the gtm-enhanced plugin I got a window like 'gtm isnt the latest'.
The version-tag for gtm is 1.3.5 so it seems to be latest. 

**Describe the solution you'd like**
I would like to support home-brew for Mac.

**Comment by kilpkonn** [comment]
It should work fine with https://github.com/DEVELOPEST/gtm-jetbrains for Jetbrains if you use `gtm-core` binary from tags.
The one on brew is the original gtm app that this project is based on.

I agree that adding the app to brew would be nice but I have no experience with iOS, so I'd appreciate if anyone else could do it.

**Comment by hu1buerger** [comment]
brew would be MacOS and I can take a look at it. Just wanted to know if there would be interest.
@kilpkonn

**Comment by kilpkonn** [comment]
Yeah definitely, I'd love it!
Hit me up if there's any questions etc. and I'll see if I can help as well if needed

**Comment by Korne127** [comment]
What a funny coincidence.
The last days I have thought about gtm and that I'd like it to be added to Homebrew (because I noticed I still had 1.0.2 installed and needed to manually update it), then I wanted to create in Issue here and the first thing I see is _exactly_ that issue.
Since this issue is already almost 3 months out and so far nothing has happened, I researched a bit on how to add a project to Homebrew (/Linuxbrew) and it actually is not very difficult.
I basically did everything, you just need to do some last steps (which should take less than 5 minutes) as the project owner so it can be used by Homebrew.

I'll still explain what I did and how Homebrew works:

Homebrew has different taps, which are basically libraries with projects you can install.
If you use "brew install xxx" it searches the default / main homebrew tap if xxx exists there to install it first. However, you can add other tabs / sources from where you can install projects with "brew tap <Tapsource>". If you tapped them, "brew install xxx" will also search through them.
So to make this project available for Homebrew / Linuxbrew, there are two possibilities:
1. You create an own tap. Then people will use "brew tap developest/xxx" to add your tap and then they can install gtm via "brew install gtm"
2. You get gtm into the official default / main tap. Then they just need to use "brew install gtm", however, the requirements for that are higher.

For both of these, you need a "formula", basically a script telling the commando line on how to download.

If you wanna know about how to create a formula for this project, there are these helpful tutorials:
https://docs.brew.sh/Formula-Cookbook
https://medium.com/ballerina-techblog/how-to-create-your-own-homebrew-package-or-formula-8dfbf8e001d3
The first one (official documentation) is especially important if you want to get gtm into the main tap. For that, there are additional requirements (e.g. a test).

However, the original gtm already has a brew formula, which you can use with few adjustments: https://github.com/git-time-metric/homebrew-gtm/blob/master/gtm.rb

I used that formula and adjusted it to this project (homepage, version, sha hashes and url) plus I added the licence information.
Notice that this formula still lacks some requirements to add it to the official tap. You can use this one for an own tap now and add it into the official tap sometimes later though.

```rb
class Gtm < Formula
  desc 'Simple, seamless, lightweight time tracking for all your git projects'
  homepage 'https://github.com/DEVELOPEST/gtm-core'
  license "MIT"

  version 'v1.0.3'
  sha256Mac = '3153d874d64e735ffb96538eef16696b5354b9d46192f271325dce1507a683e7'
  sha256Linux = '65a2ac04a5c14b155924df17ce3a910007c18f36c1209e24e506443732cdbf4e'

  os = ''
  if OS.mac? then
      os = 'macOS'
      sha256 "#{sha256Mac}"
  elsif OS.linux? then
      os = 'linux'
      sha256 "#{sha256Linux}"
  end
  url "https://github.com/DEVELOPEST/gtm-core/releases/download/#{Gtm.version}/gtm-#{os}.zip"

  def install
    bin.install 'gtm'
  end

end
```

There is just one thing you need to adjust:
This formula searches for "gtm-macOS.zip" and "gtm-linux.zip" in the GitHub release of v1.0.3
However, you named them inconsistently:
<img width="239" alt="image" src="https://user-images.githubusercontent.com/33464213/148427545-a4e41093-2e65-4128-9df3-8e7fdcc42568.png">

For this formula to work, you need to rename "gtm-core-macOS.zip" to "gtm-macOS.zip".
I would also strongly recommend to rename "gtm-core_1.0.3_amd64.deb" to "gtm-amd64.deb" and "gtm-1.0.3-64.msi" to "gtm-64.msi" so the naming scheme is more consistent.

If you did that, the formula is correct and should download gtm correctly via brew. The last thing you need to do is upload the formula.

I'll tell you how to do your own tap. If you want to add gtm to the official tap, you need to add more information to it and request it to be merged then. I think that is a good idea and if you want that, I can try to edit the formula and make such an appeal in a few weeks, I just don't have the time right now.

So your own tap is basically just a GitHub repository. If you create the GitHub repository "homebrew-xxx" and just put the file as gtm.rb in it, it is a valid tap you can tap with "brew tap developest/xxx"

So the only thing you need to do is creating the repository and putting the file in it.
If you want to program other things with DEVELOPEST as well and get them into the same tap, you might chose a more general name such as "homebrew-utils" (then the tap command is "brew tap developest/utils").
But if you do not currently have plans for that, I would rather recommend to name the repository "homebrew-gtm" (then the tap command is "brew tap developest/gtm").

**Comment by Korne127** [comment]
As a TL;DR, this is basically a clear to do list on what needs to be done so you can download gtm via Homebrew and Linuxbrew:

1. Create a repository named "homebrew-gtm".
2. Put the file gtm.rb into the repository:
(Since GitHub doesn't allow .rb files to be uploaded, it is zipped)
[gtm.rb.zip](https://github.com/DEVELOPEST/gtm-core/files/7823859/gtm.rb.zip)
3. Rename the macOS releases of v1.0.3 into "gtm-macOS.zip" (preferably also the other releases for a more consistent naming scheme as I wrote in the upper post)

(4. Edit the README.md file of gtm to show how you can download it via Homebrew and Linuxbrew (I can also just do this via pull request if you do the other steps))

**Comment by kilpkonn** [comment]
Big thanks for detailed guide. I'll do the rename and create `homebrew-gtm` repo, I can also give you permissions to it as I personally don't use brew so I'm gonna be always out of loop with that...

**Comment by kilpkonn** [comment]
I've renamed assets in release and you should have invite with Maintainer access to https://github.com/DEVELOPEST/homebrew-gtm so feel free to set it up. I decided I'm not gonna put the script as I wont test it so it would altogether make more sense if someone more familiar with the subject could do it.
Once you have it working there submit a simple PR against this repo with updated instruction to install and I'll merge
Also if there is anything more I should do comment below! :point_right:

**Comment by Korne127** [comment]
Thanks!
I uploaded the script with a readme in homebrew-gtm and tested it early; it worked without any problems :D
I also updated the GTM readme and I'll do a pull request for that now.
